### ISSUE TITLE
Alternate/manual profiles not supported

### ISSUE THREAD

**Issue by davereid** [turnerlabs/fargate#32]
I have multiple AWS profiles saved in my ~/.aws/credentials file, but the fargate command does not allow me to specify a `--profile` parameter like the `awscli` commands allow me to do.

**Comment by davereid** [comment]
After more investigation setting my AWS_PROFILE bash variable seems to resolve this. I just need to remember to use it every time.

**Comment by jritsema** [comment]
Yep.  The standard aws sdk rules apply.

https://github.com/turnerlabs/fargate#credentials
