### ISSUE TITLE
Support for Fargate secretes

### ISSUE THREAD

**Issue by robertaves** [turnerlabs/fargate#37]
We have added secretes to an existing task definition and once deploying with with the cli, it appears to blow them away, breaking the service requiring them. 

Is this in the road map at all?

**Comment by robertaves** [comment]
Thanks for the quick response John. The link provided is exactly what I’m
referring to. Thanks a lot, I’ll follow the repo for any updates.

**Comment by bjohnso5** [comment]
After doing a bit of analysis, it seems this would be fixed just by updating `aws-sdk-go` to a build >= [1.15.77](https://github.com/aws/aws-sdk-go/releases/tag/v1.15.77). This is the first release that includes the update to the ContainerDefinition struct to add Secrets:

```golang
// The secrets to pass to the container.
Secrets []*Secret `locationName:"secrets" type:"list"`
```

I'm attempting to put together a PR with an associated test case now, but this is my first golang adventure.

**Comment by jritsema** [comment]
@bjohnso5 @robertaves here's the pre-release build (`v0.6.0-pre-3-g230b984`).  Feel free to give it a whirl and let me know if you find any issues with it.  I'll try to get the master release out by Friday.

```
curl -s beta.get-fargate.turnerlabs.io | sh
```

**Comment by bjohnso5** [comment]
@jritsema I have confirmed that the beta release correctly preserves secrets in existing `ContainerDefinition`s. Thanks for your help in getting this out in such a timely manner.

**Comment by ajliv** [comment]
Opened #41 to allow maintaining secrets with the CLI
