### ISSUE TITLE
Valid regions?

### ISSUE THREAD

**Issue by niklasbeinghaus** [turnerlabs/fargate#43]
I just tried to deploy a service to AWS Fargate in the eu-central-1. It doesn't work because of this limitation:
https://github.com/turnerlabs/fargate/blob/master/cmd/root.go#L47

I can't see why this should not work in other zones.

**Comment by jritsema** [comment]
Hi @niklasbeinghaus.  We just merged #42 which built `v0.6.0-pre-4-g7d97b8e` using CI/CD.  You can install that version by running this command.  Please try it out and let us know how it goes.

```
curl -s beta.get-fargate.turnerlabs.io | sh
```

**Comment by niklasbeinghaus** [comment]
Nice one! I was just about to provide a PR with pretty much exactly the same content - thanks for answering so quickly.

**Comment by jritsema** [comment]
@niklasbeinghaus Please try the latest pre-release build and let me know.
```
curl -s beta.get-fargate.turnerlabs.io | sh
```

**Comment by niklasbeinghaus** [comment]
Yup, I prepared the same fix, wanted to add tests, you were faster again^^ Thanks!

**Comment by jritsema** [comment]
Resolved in https://github.com/turnerlabs/fargate/releases/tag/v0.6.0
