### ISSUE TITLE
New container definition properties missing in new task definitions

### ISSUE THREAD

**Issue by shivpatel** [turnerlabs/fargate#45]
Not seeing values like `stopTimeout` make it to the new task definition revision when running `fargate service deploy`.

**Comment by jritsema** [comment]
After reading the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html), it appears that the `stopTimeout` parameter
```
...is available for tasks using the Fargate launch type in the Ohio (us-east-2) region only 
```
I tested it in us-east-2 and it works.
