### ISSUE TITLE
Pulling region from aws configure

### ISSUE THREAD

**Issue by nodesocket** [turnerlabs/fargate#49]
If I set the region via:

```
aws configure set region "us-west-2"
```

Does fargate cli pull the region from `aws configure`?

**Comment by nodesocket** [comment]
Just tested and looks like it does not pull from `aws configure`. I had to explicitly set the region as an argument.

**Comment by jritsema** [comment]
It just uses the [aws go sdk to get region and credentials](https://github.com/turnerlabs/fargate#credentials) which I don't think looks for region in the credentials file.  We typically just `export AWS_DEFAULT_REGION=us-west-2` so we don't have to worry about it.

**Comment by nodesocket** [comment]
Yup ended up with:

```
export AWS_DEFAULT_REGION=$(aws configure get region)
```
