### ISSUE TITLE
`repositoryCredentials` is not carried forward when deploying a new image

### ISSUE THREAD

**Issue by n0n0x** [turnerlabs/fargate#59]
I would love to help with this, but I don't know much about Golang. I tried and I have reached a limit of what I know and I can do. So I am opening this issue so someone with better understanding of Golang can fix it. Seems to be a fairly easy fix I think but requires understanding about some Golang concepts that I am not familiar with.

**Description**
We are using dockerhub instead of ECR for ease of use (we have same service un multiple AWS regions, and ECR is per-region only). AWS Fargate supports private registries as reported [here](https://aws.amazon.com/about-aws/whats-new/2018/09/aws-fargate-now-supports-private-registry-authentication/)

For this, we have to specify a `repositoryCredentials` in the `containerDefinition` ([doc](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html)).

**Problem**
The problem is that when deploying the new image, the new TaskDefinition release does not include the `repositoryCredentials` that was set in the previous release.

**Command**
ncd service deploy --service $servicename --cluster $clustername -i $dockerhub_image --region $regions -v

**Result**
Service gets deployed, but the created task definition doesn't contain `repositoryCredentials`.

**Observations**
Using the `-v` option, I can see that the AWS API response for the previous task definition that is obtained from [here](https://github.com/turnerlabs/fargate/blob/e05ffe7005ef14be008066c53c1e10de154690f2/ecs/task_definition.go#L226) includes the proper `repositoryCredentials` but when I print to console the `dtd` variable using `console.Info("--- Resp: %#v", dtd)`, `repositoryCredentials` is not there.

**Expected Result**
The expected result should be that the `repositoryCredentials` parameter should be carried forward to the new registered `TaskDefinition`

**Comment by n0n0x** [comment]
Found that using the latest aws-sdk-go library works great

**Comment by jritsema** [comment]
Great @n0n0x, glad to hear it!
