### ISSUE TITLE
fargate deploy does not remove old task definitions

### ISSUE THREAD

**Issue by leonardehrenfried** [turnerlabs/fargate#64]
Perhaps this is down to me not understanding the tool correctly but once I switched to the CLI's `fargate deploy` from the ordinary terraform deployment, I noticed that old task definition versions stay around.

![Screenshot from 2020-10-28 12-56-12](https://user-images.githubusercontent.com/151346/97433387-b8cb2880-191d-11eb-87d3-f2eaa238495a.png)

In practice this is not a huge problem apart from one issue: when you stop a container (for example to force a reload due to a secret having changed) then an old task definition is started.

Is this behaving as expected?

Is there a CLI command to remove or deactivate the old task definitions?

**Comment by jritsema** [comment]
Hi @leonardehrenfried, you can [deregister task definitions](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deregister-task-definition.html) using the aws cli, but unfortunately not using the fargate cli. 

> when you stop a container (for example to force a reload due to a secret having changed) then an old task definition is started.

That is odd.  I have not experienced that behavior before.  The `service restart` command calls aws UpdateService with the forceNewDeployment flag.  This should start a new container using the existing task definition.  I'm not sure how an old task definition could be used.

**Comment by leonardehrenfried** [comment]
Ok, thanks for the quick response!

I'm going to double check what exactly is happening - maybe my observation was not correct.

**Comment by leonardehrenfried** [comment]
I could not reproduce it anymore. I was probably wrong.
